### ISSUE TITLE
Questions about the EMA process for BN statics

### ISSUE THREAD

**Issue by tengteng95** [LeeDoYup/FixMatch-pytorch#10]
Thanks for your nice work! I am a little confused about **why we need to copy the bn statics (mean/var) from the student net to the ema teacher net.** I tried to remove the ema copy process for BN in the ema teacher net by 
removing these two lines [BN EMA Update](https://github.com/LeeDoYup/FixMatch-pytorch/blob/8a6bf4d1723c1ad98048a26f3e9cd6f1f30b36dd/models/fixmatch/fixmatch.py#L78), but leading to much worse performance. Could you please show me why this happens? Thanks!

**Comment by LeeDoYup** [comment]
Hello.
The running statistics of BN are computed and updated in moving average manner durning training.

It is because there is no assumption on batch size for the inference in test time.
