### ISSUE TITLE
Impossible to avoid including labelled data in unlabelled data 

### ISSUE THREAD

**Issue by learning-luke** [LeeDoYup/FixMatch-pytorch#11]
While the flag 'include_lb_to_ulb' in get_ssl_dset is meant to do this, 'ulb_dset' is set with 'data' as opposed to 'ulb_data'.

This: 
`ulb_dset = BasicDataset(data, targets, num_classes, transform, use_strong_transform, strong_transform, onehot)`

should be:
`ulb_dset = BasicDataset(ulb_data, targets, num_classes, transform, use_strong_transform, strong_transform, onehot)`

**Comment by LeeDoYup** [comment]
Thank you for pointing out.
I didn't update it into this public repo. (only fix in my private...)

Thx for the contributing !!

**Comment by LeeDoYup** [comment]
`ulb_dset = BasicDataset(ulb_data, ulb_targets, num_classes, transform, use_strong_transform, strong_transform, onehot)`
is used.

**Comment by learning-luke** [comment]
I'm glad I could help!
