### ISSUE TITLE
argparse issues

### ISSUE THREAD

**Issue by qianlanwyd** [LeeDoYup/FixMatch-pytorch#13]
You can find solutions here
https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--a", type=bool, default=True)
args = parser.parse_args()
print(args)

def main():
    i=0

if __name__ == '__main__':
        main()

(fixmatch_pytorch) 20M19029@login1:/gs/hs0/tga-tslab/wyidong> python test.py --a False
Namespace(a=True)

**Comment by LeeDoYup** [comment]
I know this issue, but it is not still updated.
I will edit this issue, related with argparse and bool type instance, considering the user scenario.

I will update it with

```
--hard_label --> --soft_label (action= store_false)
--from_name --> action: store true

````

**Comment by LeeDoYup** [comment]
deactivated issue.
