### ISSUE TITLE
how to cite your repo?

### ISSUE THREAD

**Issue by qianlanwyd** [LeeDoYup/FixMatch-pytorch#14]
I reproduced pi model, pseudo label, meanteacher, mixmatch, uda, remixmatch, fixmatch based on your open source codes. May I ask how to cite your repo?

**Comment by LeeDoYup** [comment]
I think you can just follow the descriptions in this [link](https://www.wikihow.com/Cite-a-GitHub-Repository).
I am appreciate for your using my repo !
