### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by YBZh** [LeeDoYup/FixMatch-pytorch#3]
Nice work !!  The results seem really attractive.  
It takes me more than one hour to train for 10K iterations based on ONE M40 GPU, thus the total training time for ONE Cifar-10 experiment is about 2^20 / 10K * 1 h = 100 h ~ 4 days !! Is this normal ?? 

As you said, CIFAR10 training takes about 16 hours (0.7 days) with V100x4 GPUs. Does your training make the full utilization of all the FOUR GPUs or just based on ONE of them ??

**Comment by LeeDoYup** [comment]
YES It is normal.
The training iterations are > 10,000,000 with batch size 64 * 8.

Trivial supervised training of CIFAR has 50000/batch_size in a epoch.
Thus, consistency regularization requires much more iterations of training.

We checked our code use full data parallelism with DDP, and there is no computational bottleneck (all GPUs keep > 90% volatility in training).

**Comment by LeeDoYup** [comment]
It is the reason why we release the trained model to contribute AI society.

**Comment by LeeDoYup** [comment]
@YBZh  We are on testing this branch dev/speedup https://github.com/LeeDoYup/FixMatch-pytorch/tree/dev/speedup .
We expect that it increases the speed of training about 15 % w/o performance changes.
After checking all the experiments, we will merge it to the master branch.
(Meanwhile, we already know the computation is not logically different in pytorch, and if you need it, feel free to use the branch.)
