### ISSUE TITLE
What are the important factors to improve performance?

### ISSUE THREAD

**Issue by LiJunnan1992** [LeeDoYup/FixMatch-pytorch#7]
Hi, thanks for the amazing and well-documented code!

I have been using the code from valencebond, but cannot reproduce the paper's results, especially for CIFAR-100. 

What do you think are the important factors to reproduce the paper's results? Is it because of some implementation details of the EMA model?

**Comment by LeeDoYup** [comment]
I didn't compare the implementation in a case-by-case manner.
However, i guess you have to increase the model size when you train CIFAR-100 datasets.
(I also checked that official repo has lots of issue about the size of WRN in CIFAR-100 training.)

In my case, I use `--widen_factor 8`.

**Comment by QiushiYang** [comment]
> I didn't compare the implementation in a case-by-case manner. However, i guess you have to increase the model size when you train CIFAR-100 datasets. (I also checked that official repo has lots of issue about the size of WRN in CIFAR-100 training.)
> 
> In my case, I use `--widen_factor 8`.

I trained the CIFAR-100 with WRN-28-8 but found that the training time was much slower than training CIFAR-10 with WRN-28-2 using the same number of images (above 3-4 x slower). Did you also find this issue?

**Comment by LeeDoYup** [comment]
@QiushiYang  Thanks for using my codes.
Yes, CIFAR100 has to be trained on WRN-28-8.
Also, the training time is 3x - 4x longer than the time of WRN-28-2, because WRN-28-8 has about 24M parameters (WRN-28-2 has 1.5M).
FixMatch has a limitation on training large networks because of its inefficient SSL training.
