### ISSUE TITLE
Current weak transformation in ssl_dataset.py only correct for 32x32 images

### ISSUE THREAD

**Issue by gomezzz** [LeeDoYup/FixMatch-pytorch#9]
Hey!

Thank you for the great code, it's very nice! We found one minor problem adapting it to other datasets, that probably can be fixed easily but can mess up results quite a bit (without any error):

In [ssl_dataset.py](https://github.com/LeeDoYup/FixMatch-pytorch/blob/main/datasets/ssl_dataset.py) line 25 you define one of the "weak" transformations as

`transforms.RandomCrop(32, padding=4)`

We suspect this is intended as the translation in the original code. However, for larger images this is a (probably unintentionally) strong augmentation. Should probably just be adaptive to img size or use a different transformation?

Might save others some time :)

Thanks!

**Comment by LeeDoYup** [comment]
Hello @gomezzz .
Yes, you are right.
The code actually aim to process CIFAR datasets or other (32x32) size of images.
If you use another dataset, you can adjust the parts of augmentations.

Thank you.

**Comment by LeeDoYup** [comment]
For example,
I am working on ImageNet dataset (it's not released in public, but i plan to do),
the randomcrop size is 224.

I also re-implement another BasicDataset class according to the target dataset.
